/***************************************************/
/******** Author      : Muhammed Hesham *********/
/******** Date        : 5 / 8 / 2023          *********/
/******** version     : 1.0 V              *********/
/******** Description : DIO configration       *********/
/***************************************************/

#ifndef INCLUDE_MCAL_DIO_DIO_CFG_H_
#define INCLUDE_MCAL_DIO_DIO_CFG_H_

#define DIO_OUTPUT 1
#define DIO_INPUT  0

#define DIO_CFG_HIGH  1 //if configured as output
#define DIO_LOW       0

#define DIO_PULLUP    1 //if configured as input
#define DIO_FLOATING  0

#define PORTA_PIN0_DIRECTION  DIO_OUTPUT
#define PORTA_PIN1_DIRECTION  DIO_OUTPUT
#define PORTA_PIN2_DIRECTION  DIO_OUTPUT
#define PORTA_PIN3_DIRECTION  DIO_OUTPUT
#define PORTA_PIN4_DIRECTION  DIO_OUTPUT
#define PORTA_PIN5_DIRECTION  DIO_OUTPUT
#define PORTA_PIN6_DIRECTION  DIO_OUTPUT
#define PORTA_PIN7_DIRECTION  DIO_OUTPUT

#define PORTB_PIN0_DIRECTION  DIO_INPUT
#define PORTB_PIN1_DIRECTION  DIO_INPUT
#define PORTB_PIN2_DIRECTION  DIO_INPUT
#define PORTB_PIN3_DIRECTION  DIO_INPUT
#define PORTB_PIN4_DIRECTION  DIO_INPUT
#define PORTB_PIN5_DIRECTION  DIO_INPUT
#define PORTB_PIN6_DIRECTION  DIO_INPUT
#define PORTB_PIN7_DIRECTION  DIO_INPUT

#define PORTC_PIN0_DIRECTION  DIO_INPUT
#define PORTC_PIN1_DIRECTION  DIO_INPUT
#define PORTC_PIN2_DIRECTION  DIO_INPUT
#define PORTC_PIN3_DIRECTION  DIO_INPUT
#define PORTC_PIN4_DIRECTION  DIO_INPUT
#define PORTC_PIN5_DIRECTION  DIO_INPUT
#define PORTC_PIN6_DIRECTION  DIO_INPUT
#define PORTC_PIN7_DIRECTION  DIO_INPUT

#define PORTD_PIN1_DIRECTION  DIO_OUTPUT
#define PORTD_PIN2_DIRECTION  DIO_OUTPUT
#define PORTD_PIN0_DIRECTION  DIO_OUTPUT
#define PORTD_PIN3_DIRECTION  DIO_OUTPUT
#define PORTD_PIN4_DIRECTION  DIO_INPUT
#define PORTD_PIN5_DIRECTION  DIO_INPUT
#define PORTD_PIN6_DIRECTION  DIO_INPUT
#define PORTD_PIN7_DIRECTION  DIO_INPUT


/* Direction OUTPUT :- DIO_CFG_HIGH   - DIO_LOW */
/* Direction INPUT  :- DIO_PULLUP - DIO_FLOATING */
#define PORTA_PIN0_VALUE  DIO_LOW
#define PORTA_PIN1_VALUE  DIO_LOW
#define PORTA_PIN2_VALUE  DIO_LOW
#define PORTA_PIN3_VALUE  DIO_LOW
#define PORTA_PIN4_VALUE  DIO_LOW
#define PORTA_PIN5_VALUE  DIO_LOW
#define PORTA_PIN6_VALUE  DIO_LOW
#define PORTA_PIN7_VALUE  DIO_LOW

#define PORTB_PIN0_VALUE  DIO_FLOATING
#define PORTB_PIN1_VALUE  DIO_FLOATING
#define PORTB_PIN2_VALUE  DIO_FLOATING
#define PORTB_PIN3_VALUE  DIO_FLOATING
#define PORTB_PIN4_VALUE  DIO_FLOATING
#define PORTB_PIN5_VALUE  DIO_FLOATING
#define PORTB_PIN6_VALUE  DIO_FLOATING
#define PORTB_PIN7_VALUE  DIO_FLOATING

#define PORTC_PIN0_VALUE  DIO_PULLUP
#define PORTC_PIN1_VALUE  DIO_FLOATING
#define PORTC_PIN2_VALUE  DIO_FLOATING
#define PORTC_PIN3_VALUE  DIO_FLOATING
#define PORTC_PIN4_VALUE  DIO_FLOATING
#define PORTC_PIN5_VALUE  DIO_FLOATING
#define PORTC_PIN6_VALUE  DIO_FLOATING
#define PORTC_PIN7_VALUE  DIO_FLOATING

#define PORTD_PIN0_VALUE  DIO_LOW
#define PORTD_PIN1_VALUE  DIO_LOW
#define PORTD_PIN2_VALUE  DIO_LOW
#define PORTD_PIN3_VALUE  DIO_LOW
#define PORTD_PIN4_VALUE  DIO_LOW
#define PORTD_PIN5_VALUE  DIO_LOW
#define PORTD_PIN6_VALUE  DIO_LOW
#define PORTD_PIN7_VALUE  DIO_LOW
#endif /* INCLUDE_MCAL_DIO_DIO_CFG_H_ */
